// components/FloatingMicButton.styles.ts
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        position: 'absolute',
        bottom: 30,
        right: 20,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 1000,
    },
    micButton: {
        width: 60,
        height: 60,
        borderRadius: 30,
        elevation: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        zIndex: 2,
    },
    touchArea: {
        width: '100%',
        height: '100%',
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 30,
    },
    borderRing: {
        position: 'absolute',
        width: 70,
        height: 70,
        borderRadius: 35,
        borderWidth: 2,
        borderColor: 'rgba(255, 89, 0, 0.3)',
        zIndex: 1,
    },
    glowEffect: {
        position: 'absolute',
        width: 90,
        height: 90,
        borderRadius: 45,
        backgroundColor: '#FF5900',
        shadowColor: '#FF5900',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        elevation: 0,
        zIndex: 0,
    },
    intentText: {
        marginTop: 8,
        color: '#333',
        fontSize: 12,
        backgroundColor: '#FFF',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 8,
        elevation: 2,
    },
});
